#!/usr/bin/env fish

###---Functions---###
function start_if_not_running
    if [ (pgrep -u (id -u) -x $argv[1] | wc -l) -lt 1 ]
        eval "$argv[1] &"
    end
end

###---Load xresources---###
xrdb -load ~/.config/X11/xresources

###---Flush rules---###
bspc rule -r "*"

###---Sxhkd---###
set -U SXHKD_SHELL sh
sxhkd &

###---Keyboard---###
setxkbmap -option caps:escape

if [ -x /usr/bin/numlockx ]
    /usr/bin/numlockx on
end

###---Monitors---###
set SCREENCOUNT (xrandr | grep -c "\*")

if [ "$SCREENCOUNT" -eq 2 ]
    bspc monitor DP-1 -d 2 3 4 5 6 7 8 9 0
    bspc monitor HDMI-2 -d 1
    if [ -f "$HOME/.local/bin/screen_desktop" ]
        screen_desktop
    end
    if [ -f "$HOME/.local/bin/polybar-desktop" ]
        polybar-desktop
    end
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
    if [ -f "$HOME/.local/bin/screen" ]
        screen
    end
    if [ -f "$HOME/.local/bin/polybar-laptop" ]
        polybar-laptop
    end
end

###---Wallpaper & opacity---###
~/.local/bin/wallpaper
wal -n -R
picom -b

###---Global Settings---###
. ~/.cache/wal/colors.fish
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

###---Desktop Settings----###
bspc config border_width 2
bspc config window_gap 4

###---Rules---###
bspc rule -a "Syncthing GTK" state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a float state=floating
bspc rule -a fullscreen state=fullscreen
bspc rule -a Spotify desktop='^4'
bspc rule -a Spt desktop='^4'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Brave-browser desktop='^9'
bspc rule -a scratchpad sticky=on state=floating
bspc rule -a scratchmacs sticky=on state=floating

###---Autostart---###
start_if_not_running dunst
start_if_not_running unclutter
start_if_not_running nm-applet
start_if_not_running pasystray
start_if_not_running redshift-gtk
start_if_not_running syncthing-gtk
start_if_not_running caffeine
start_if_not_running brave

pkill -f cleanfullscreen
~/.local/bin/cleanfullscreen &

###---System lock---###
pkill -f xss-lock
xss-lock -n ~/.local/bin/lock -- ~/.local/bin/lock &
pkill -f xautolock
xautolock -time 10 -locker ~/.local/bin/lock &

###---Misc---###
# Needed for Jetbrains products to work
wmname LG3D &

# Enable bspswallow
pidof bspswallow || bash bspswallow &
