#!/usr/bin/env fish

# Load wal colours
. ~/.cache/wal/colors.fish
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

sxhkd &

# Set screen orientation if second monitor is connected
set SCREENCOUNT (xrandr | grep -c "\*")

# If multi screen add special mode for monitor so it supports 1440p over HDMI
if [ "$SCREENCOUNT" -eq 2 ]
    bspc monitor DP-1 -d 2 3 4 5 6 7 8 9 10
    bspc monitor HDMI-2 -d 1
    if [ -f "$HOME/.local/bin/screen_desktop" ]
        screen_desktop
    end
    if [ -f "$HOME/.local/bin/polybar-desktop" ]
        polybar-desktop
    end
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
    if [ -f "$HOME/.local/bin/screen" ]
        screen
    end
    if [ -f "$HOME/.local/bin/polybar-laptop" ]
        polybar-laptop
    end
end

xcompmgr &

if [ -e ~/.cache/wall1.png ] && [ -e ~/.cache/wall2.png ]
    xwallpaper --output HDMI-2 --zoom ~/.cache/wall2.png --output DP-1 --zoom ~/.cache/wall1.png &
else if [ -e ~/.cache/wall1.png ]
    xwallpaper --output eDP1 --zoom ~/.cache/wall1.png &
end

unclutter &
dunst &

redshift-gtk &
nm-applet &
syncthing-gtk &
gpodder &
alacritty --class Spt,Spt -e spt &

# system lock
xss-lock -n ~/.local/bin/lock -- ~/.local/bin/lock &
xautolock -time 10 -locker ~/.local/bin/lock &

if [ -e /usr/bin/brave ]
    brave &
else
    if [ -e /usr/bin/firefox ]
        firefox &
    else if [ -e /usr/bin/iceweasel ]
        iceweasel &
    end
end

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a "Syncthing GTK" state=floating
bspc rule -a Gimp state=floating
bspc rule -a Gpodder desktop='^4'
bspc rule -a Spotify desktop='^4'
bspc rule -a Spt desktop='^4'
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Brave-browser desktop='^9'
bspc rule -a scratchpad sticky=on state=floating
bspc rule -a scratchmacs sticky=on state=floating
