# Shell variables
# Generated by 'wal'
set -g wallpaper "{wallpaper}"

# Special
set -g background "{background}"
set -g foreground "{foreground}"
set -g cursor '{cursor}'

# Colors
set -g color0 "{color0}"
set -g color1 "{color1}"
set -g color2 "{color2}"
set -g color3 "{color3}"
set -g color4 "{color4}"
set -g color5 "{color5}"
set -g color6 "{color6}"
set -g color7 "{color7}"
set -g color8 "{color8}"
set -g color9 "{color9}"
set -g color10 "{color10}"
set -g color11 "{color11}"
set -g color12 "{color12}"
set -g color13 "{color13}"
set -g color14 "{color14}"
set -g color15 "{color15}"

# FZF colors
set -g -a FZF_DEFAULT_OPTS "--color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255 --color info:7,prompt:2,spinner:1,pointer:232,marker:1"

# Fix LS_COLORS being unreadable.
set -g -a LS_COLORS ":su=30;41:ow=30;42:st=30;44:"
