# Shell variables
# Generated by 'wal'
set -xg wallpaper "{wallpaper}"

# Special
set -xg background "{background}"
set -xg foreground "{foreground}"
set -xg cursor '{cursor}'

# Colors
set -xg color0 "{color0}"
set -xg color1 "{color1}"
set -xg color2 "{color2}"
set -xg color3 "{color3}"
set -xg color4 "{color4}"
set -xg color5 "{color5}"
set -xg color6 "{color6}"
set -xg color7 "{color7}"
set -xg color8 "{color8}"
set -xg color9 "{color9}"
set -xg color10 "{color10}"
set -xg color11 "{color11}"
set -xg color12 "{color12}"
set -xg color13 "{color13}"
set -xg color14 "{color14}"
set -xg color15 "{color15}"

# FZF colors
set -xg -a FZF_DEFAULT_OPTS "--color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255 --color info:7,prompt:2,spinner:1,pointer:232,marker:1"

# Fix LS_COLORS being unreadable.
set -xg -a LS_COLORS ":su=30;41:ow=30;42:st=30;44:"
