#!/usr/bin/env bash

function generateWallpaper() {
	notify-send.py --hint string:image-path:"$2" --replaces-process setwallpaper -a sxiv "Setting wallpaper" &
	nitrogen --head="$1" --set-zoom-fill --save "$2"

	# Only generate wal color schemes for main monitor
	if [ "$1" == 0 ]; then
		notify-send.py --hint string:image-path:"$2" --replaces-process setwallpaper -a sxiv "Generating wal color scheme" &
		~/.local/bin/generatewal
	fi

	notify-send.py --hint string:image-path:"$2" --replaces-process setwallpaper -a sxiv "Wallpaper set" &
}

while read -r file; do
	case "$1" in
	"C-c")
		echo -n "$file" | xclip -selection clipboard
		notify-send.py --hint string:image-path:"$file" -a sxiv "Added to clipboard" &
		;;
	"C-l")
		notify-send.py --hint string:image-path:"$file" -a sxiv "Generating lock image" &
		generate-lock-image "$file"
		notify-send.py --hint string:image-path:"$file" -a sxiv "Lock image generated" &
		;;
	"C-w")
		generateWallpaper 0 "$file"
		;;
	"C-1")
		generateWallpaper 0 "$file"
		;;
	"C-2")
		generateWallpaper 1 "$file"
		;;
	esac
done
